path: '/content/gdrive/My Drive/data/object'  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

names:
  0: person
  1: person